[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma", "bcrypt"]
  included_files = ["prisma/schema.prisma", "node_modules/.prisma/**"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/chatbot"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *;"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[edge_functions]]
  function = "chatbot"
  path = "/chatbot"